services:
  # --- SPARK MASTER (Imagem Oficial) ---
  spark-master:
    image: apache/spark:3.5.1
    container_name: spark-master
    user: root # Garante permissões para ler os ficheiros no teu Mac e Windows
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080" # UI do Master
      - "7077:7077" # Porta para submissão de Jobs
    volumes:
      - ./src/jobs:/opt/spark/jobs # caminho interno é /opt/spark/jobs
    networks:
      - climate-net

  # --- SPARK WORKER (Imagem Oficial) ---
  spark-worker:
    image: apache/spark:3.5.1
    container_name: spark-worker
    user: root
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    depends_on:
      - spark-master
    volumes:
      - ./src/jobs:/opt/spark/jobs
    networks:
      - climate-net

  # --- MINIO (Storage S3) ---
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    networks:
      - climate-net

  # --- POSTGRES (Base de Dados) ---
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=climate_db
    ports:
      - "5432:5432"
    networks:
      - climate-net

  # --- GRAFANA (Visualização) ---
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - climate-net

# --- REDES ---
networks:
  climate-net:
    driver: bridge